hook/event -> reset statics 
reset statics -- resub: resubscribe events to TimeManager
resub -> countdownTick
resub -> SDTick

resub: "" {
    width: 1
    height: 1
}

reset statics: "" {
text: |`
**reset statics**
- cyl size
- timer
`|
}

countdownTick: "" {
    text: |`
    **countdownTick**

    decr timer, spawn cyl if time up
    `|
}

SDTick: "" {
    style: {
        stroke-dash: 3
    }
    text: |`
    **SDTick** (only run if countdown done)

    - shrink cyl
    - damage players sometimes
    `|
}
